---
title: "Analysis Dataset HMS"
output: html_document
date: "2025-09-18"
---

```{r}
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = "3.21")

# Install Bioconductor required packages
BiocManager::install("DESeq2")
BiocManager::install("EnhancedVolcano")
BiocManager::install("SingleCellExperiment")
BiocManager::install("miloR")
BiocManager::install("clusterProfiler")
BiocManager::install("org.Mm.eg.db")
BiocManager::install("sccomp")
BiocManager::install("speckle")

# Install CRAN required packages
install.packages("pheatmap")
install.packages("ggalluvial")
install.packages("msigdbr")
install.packages("ggvenn")
install.packages("tidyverse")

install.packages('devtools')
devtools::install_github('immunogenomics/presto')

# Load libraries
library(Seurat)
library(tidyverse)
library(pheatmap)
library(RColorBrewer)
library(cowplot)
library(dplyr)
library(DESeq2)
library(EnhancedVolcano)
library(SingleCellExperiment)
library(miloR)
library(ggalluvial)
library(clusterProfiler)
library(org.Mm.eg.db)
library(msigdbr)
library(ggvenn)
library(sccomp)
library(speckle)
library(ggplot2)
library(patchwork)
library(presto)
library(Matrix)
library(DESeq2)
library(EnhancedVolcano)
```

Merged together the wildtype and mutant datasets for future analysis 
```{r}
mt1.data <- Read10X("/Users/hannahwilcox/Documents/sample_scRNA_sequencing_data/mt1")
mt1 <- CreateSeuratObject(counts = mt1.data, project = "mt1", min.cells = 3, min.features = 200)

mt2 <- Read10X("/Users/hannahwilcox/Documents/sample_scRNA_sequencing_data/mt2")
mt2 <- CreateSeuratObject(counts = mt2, project = "mt2", min.cells = 3, min.features = 200)

mt3 <- Read10X("/Users/hannahwilcox/Documents/sample_scRNA_sequencing_data/mt3")
mt3 <- CreateSeuratObject(counts = mt3, project = "mt3", min.cells = 3, min.features = 200)

wt1 <- Read10X("/Users/hannahwilcox/Documents/sample_scRNA_sequencing_data/wt1")
wt1 <- CreateSeuratObject(counts = wt1, project = "wt1", min.cells = 3, min.features = 200)

wt2 <- Read10X("/Users/hannahwilcox/Documents/sample_scRNA_sequencing_data/wt2")
wt2 <- CreateSeuratObject(counts = wt2, project = "wt2", min.cells = 3, min.features = 200)

```


Doing QC
```{r}
QC = function(sample) {
  # Remove unwanted cells
  sample[["percent.mt"]] <- PercentageFeatureSet(sample, pattern = "^mt:")
  sample <- subset(sample, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 10)

  # Normalize the dataset using standard normalization method 
  sample <- NormalizeData(sample, normalization.method = "LogNormalize", scale.factor = 1e4)

  # Limit to only most variable features to shrink dataset 
  sample <- FindVariableFeatures(sample, selection.method = 'vst', nfeatures = 2000)

  # Scale to mean 0 and variance 1 so highly expressed genes don't dominate 
  all.genes <- rownames(sample)
  sample <- ScaleData(sample, features = all.genes)
  return(sample)
  }

mt1 = QC(mt1)
# Perform PCA 
mt1 <- RunPCA(mt1, features = VariableFeatures(object = mt1))

# Assess ElbowPlot for dimensions to maintain 
ElbowPlot(mt1)

# Cluster with UMAP 
mt1 <- FindNeighbors(mt1, dims = 1:5)
mt1 <- FindClusters(mt1, resolution = 0.5)
mt1 <- RunUMAP(mt1, dims = 1:5)
DimPlot(mt1, reduction = 'umap')

mt2 = QC(mt2)
# Perform PCA 
mt2 <- RunPCA(mt2, features = VariableFeatures(object = mt2))

# Assess ElbowPlot for dimensions to maintain 
ElbowPlot(mt2)

# Cluster with UMAP 
mt2 <- FindNeighbors(mt2, dims = 1:5)
mt2 <- FindClusters(mt2, resolution = 0.5)
mt2 <- RunUMAP(mt2, dims = 1:5)
DimPlot(mt2, reduction = 'umap')

mt3 = QC(mt3)
# Perform PCA 
mt3 <- RunPCA(mt3, features = VariableFeatures(object = mt3))

# Assess ElbowPlot for dimensions to maintain 
ElbowPlot(mt3)

# Cluster with UMAP 
mt3 <- FindNeighbors(mt3, dims = 1:5)
mt3 <- FindClusters(mt3, resolution = 0.5)
mt3 <- RunUMAP(mt3, dims = 1:5)
DimPlot(mt3, reduction = 'umap')

wt1 = QC(wt1)
# Perform PCA 
wt1 <- RunPCA(wt1, features = VariableFeatures(object = wt1))

# Assess ElbowPlot for dimensions to maintain 
ElbowPlot(wt1)

# Cluster with UMAP 
wt1 <- FindNeighbors(wt1, dims = 1:5)
wt1 <- FindClusters(wt1, resolution = 0.5)
wt1 <- RunUMAP(wt1, dims = 1:5)
DimPlot(wt1, reduction = 'umap')

wt2 = QC(wt2)
# Perform PCA 
wt2 <- RunPCA(wt2, features = VariableFeatures(object = wt2))

# Assess ElbowPlot for dimensions to maintain 
ElbowPlot(wt2)

# Cluster with UMAP 
wt2 <- FindNeighbors(wt2, dims = 1:5)
wt2 <- FindClusters(wt2, resolution = 0.5)
wt2 <- RunUMAP(wt2, dims = 1:5)
DimPlot(wt2, reduction = 'umap')

```
Merge mutant and wildtype datasets for analysis

```{r}
all <- merge(mt1, y = c(mt2, mt3, wt1, wt2), add.cell.id = c("mt1", "mt2", "mt3", "wt1", "wt2"), merge.data = TRUE)

all <- FindVariableFeatures(all, selection.method = 'vst', nfeatures = 2000)

all.genes <- rownames(all)
all <- ScaleData(all, features = all.genes)
all <- RunPCA(all, features = VariableFeatures(object = all))
ElbowPlot(all)

all <- FindNeighbors(all, dims = 1:5) # Edit dims based on ElbowPlot
all <- FindClusters(all, resolution = 0.4) 
all <- RunUMAP(all, dims = 1:5)

# Plot by sample to see if properly merged 
DimPlot(all, reduction = 'umap', label = FALSE, label.box = TRUE, split.by = "orig.ident")

```

Samples are properly merged with all samples having cells in each cluster, so no need to integrate. Can now run DEA 

```{r}
# Cell Type Analysis on Cells 
# Common genes expressed in cell types in drosophila 

# Neurons
VlnPlot(all, features = c("elav", "Fas2", "trio"))

# Glia
VlnPlot(all, features = c("repo", "glial"))

# Muscle
VlnPlot(all, features = c("Mhc"))

# Fat body
VlnPlot(all, features = c("Lsp2"))

# Ovary
VlnPlot(all, features = c("Orb", "esg"))

# Blood Cells
VlnPlot(all, features = c("Hml", "P1", "P2"))


```
0: Muscle
1: Muscle
2: Muscle 
3: Muscle
4: Neuron 
5: Neuron 
6: Neuron 
7: Neuron 
8: Neuron 
9: Neuron



```{r, Data viz}
# UMAP of sample
DimPlot(all, group.by = "orig.ident")

# UMAP clusters
p <- DimPlot(all, group.by = "seurat_clusters") + NoLegend()
LabelClusters(p, id = "seurat_clusters", fonface = "bold", size = 5,
              bg.colour = "white", bg.r = .2, force = 0)

```


```{r, clusters to celltype}
# Map clusters to celltype
# Need to add cell type column to Seurat object 
all$celltype <- NA # to create an empty column

all$celltype[all$seurat_clusters == 0] <- "Muscle"
all$celltype[all$seurat_clusters == 1] <- "Muscle"
all$celltype[all$seurat_clusters == 2] <- "Muscle"
all$celltype[all$seurat_clusters == 3] <- "Muscle"
all$celltype[all$seurat_clusters == 4] <- "Neuron"
all$celltype[all$seurat_clusters == 5] <- "Neuron"
all$celltype[all$seurat_clusters == 6] <- "Neuron"
all$celltype[all$seurat_clusters == 7] <- "Neuron"
all$celltype[all$seurat_clusters == 8] <- "Neuron"
all$celltype[all$seurat_clusters == 9] <- "Neuron"


# Check number of cells in each cluster assignment
table(all$celltype)

# Muscle Neuron 
# 13907   7475 

# Check number of cells by sample 
table(all$orig.ident)

#  mt1  mt2  mt3  wt1  wt2 
# 4155 4198 4218 4258 4553 
```

```{r, alluvial plot, fig.height=8, fig.width=10}
# UMAP celltype
Idents(all) <- "celltype"
p <- DimPlot(all) + NoLegend()
LabelClusters(p, id = "ident")

# Run in the consol 
```

# Add Cell Type Labels
```{r}
all$type <- NA # to create an empty column

all$type[all$orig.ident == "mt1"] <- "mt"
all$type[all$orig.ident == "mt2"] <- "mt"
all$type[all$orig.ident == "mt3"] <- "mt"
all$type[all$orig.ident == "wt1"] <- "wt"
all$type[all$orig.ident == "wt2"] <- "wt"

```



# Differential Expression 
```{r}
# Create a vector mapping cell -> sample and cell -> celltype
meta <- all@meta.data
# Example for Neurons only
neurons_cells <- rownames(meta)[meta$celltype == "Neuron"]
neurons <- subset(all, cells = neurons_cells)

# Aggregate to pseudobulk: sum counts per gene per sample
neurons <- JoinLayers(neurons)
counts <- GetAssayData(neurons, slot = "counts", assay = "RNA")
samples <- neurons$orig.ident
# aggregate using Matrix::rowSums on subsets:
sample_list <- split(colnames(counts), samples)
pb_counts <- sapply(sample_list, function(cols) rowSums(counts[, cols, drop=FALSE]))
# pb_counts is genes x sample matrix

coldata <- data.frame(row.names = colnames(pb_counts),
                      condition = ifelse(grepl("^mt", colnames(pb_counts)),"mt","wt"))
dds <- DESeqDataSetFromMatrix(countData = pb_counts,
                              colData = coldata,
                              design = ~ condition)
dds <- DESeq(dds)
res <- results(dds)

res_df <- as.data.frame(res) %>% 
  rownames_to_column("gene") %>%
  arrange(padj)

sig_genes <- res_df %>% filter(padj < 0.05 & abs(log2FoldChange) > 1)
head(sig_genes)

EnhancedVolcano(res_df,
    lab = res_df$gene,
    x = "log2FoldChange",
    y = "padj",
    title = "Pseudobulk DEG: Mutant vs Wildtype Neurons",
    pCutoff = 0.05,
    FCcutoff = 1,
    pointSize = 2.0,
    labSize = 3.5)
```





